# Generated by Django 5.1.2 on 2025-01-20 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_productmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
