# Generated by Django 5.1.2 on 2025-02-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_description', models.TextField()),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
        ),
    ]
