# Generated by Django 5.1.2 on 2025-02-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'model_number')},
        ),
    ]
