# Generated by Django 5.1.2 on 2025-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model_number',
            field=models.CharField(max_length=50),
        ),
    ]
