# Generated by Django 5.1.2 on 2025-02-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_brand_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
    ]
