# Generated by Django 5.1.6 on 2025-02-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
