# Generated by Django 5.1.6 on 2025-02-18 13:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD', unique=True, verbose_name='Phone number'),
        ),
    ]
