# Generated by Django 5.1.2 on 2025-01-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_album_name_alter_album_release_date'),
        ('musician', '0003_alter_instruments_instrument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musician_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musician.musician'),
        ),
    ]
