# Generated by Django 5.1.2 on 2025-01-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='music_type',
            field=models.CharField(default='Classical', max_length=30),
        ),
    ]
