# Generated by Django 5.1.2 on 2025-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_musician_music_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='instrument_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
