# Generated by Django 5.1.2 on 2025-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender_variation', models.CharField(choices=[('Female', 'Female'), ('Both', 'Both'), ('Male', 'Male')], default='Both', max_length=10)),
            ],
        ),
    ]
